### ISSUE TITLE
Roll back fileNameExtension rule in scss-lint.yml

### ISSUE THREAD

**Issue by delacruz-dev** [scm-spain/frontend-pre-commit-rules#17]
It's not needed anymore to specify the filename extension when importing `.scss` files with the latest version of the generator.

https://github.com/scm-spain/frontend-pre-commit-rules/commit/7e908849d6bb7aed168afc2ed10522ea3c173ffb#diff-e9419947d819494941dc8d981f0e128c

**Comment by davecarter** [comment]
:+1:
