### ISSUE TITLE
Let double quotes for strings

### ISSUE THREAD

**Issue by vicente-palomero** [scm-spain/frontend-pre-commit-rules#18]
Hi there, 

IMHO we should let the usage of double quotes for string instead banning them. They are useful when we want to use the single quote inside the string. Without using doubles we have to escape anytime we need the simple quote, like apostrophes or English contractions. 

I agree with lowering the level of alert from error to warning and see if we require them in the sentence. In Spanish we shouldn't use them, but in Catalan or English single quote should be more accessible.

RULE: https://github.com/scm-spain/frontend-pre-commit-rules#stringquotes
INFO: https://en.wikipedia.org/wiki/Quotation_mark

**Comment by davecarter** [comment]
:+1: Agree.
Thanks for contributing!
